created basic testing framework

diff --git a/compile b/compile
--- a/compile
+++ b/compile
@@ -6,15 +6,15 @@ YELLOW='\033[1;33m'
 NC='\033[0m' # No Color
 
 echo ""
-echo -e "${YELLOW}RUNNING BUILD${NC}"
+echo "${YELLOW}RUNNING BUILD${NC}"
 
 echo "building client:"
 gcc src/client/client.c -o build/client
 
 if [ $? -eq 0 ]; then
-	echo -e "${GREEN}success.${NC}"
+	echo "${GREEN}success.${NC}"
 else
-	echo -e "${RED}failed.${NC}"
+	echo "${RED}failed.${NC}"
 	echo ""
 	exit
 fi
@@ -23,9 +23,9 @@ echo "building server:"
 gcc src/server/server.c -o build/server
 
 if [ $? -eq 0 ]; then
-	echo -e "${GREEN}success.${NC}"
+	echo "${GREEN}success.${NC}"
 else
-	echo -e "${RED}failed.${NC}"
+	echo "${RED}failed.${NC}"
 	echo ""
 	exit
 fi
@@ -35,9 +35,27 @@ echo "building ray:"
 gcc src/ray/ray.c -o build/ray
 
 if [ $? -eq 0 ]; then
-	echo -e "${GREEN}success.${NC}"
+	echo "${GREEN}success.${NC}"
 else
-	echo -e "${RED}failed.${NC}"
+	echo "${RED}failed.${NC}"
+	echo ""
+	exit
+fi
+
+echo ""
+echo "${YELLOW}RUNNING TESTS${NC}"
+
+gcc src/tests/*.c -o build/tests
+
+if [ $? -eq 0 ]; then
+	echo "${GREEN}built.${NC}"
+
+	./build/tests
+
+	echo ""
+
+else
+	echo "${RED}failed.${NC}"
 	echo ""
 	exit
 fi
